/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Change_room_or_ward extends javax.swing.JFrame {

    Date d;
    SimpleDateFormat sdf;
    static DefaultTableModel dtm3;
    String i1 = "2";
    String type;
    String admitid;
    String roomid;
    String wid;
    String bid;

    /**
     * Creates new form admit
     */
    public Change_room_or_ward() {
        initComponents();
        exit.setContentAreaFilled(false);
        Minimize.setContentAreaFilled(false);
        load_time_and_date();
        jScrollPane1.setVisible(false);
        setwrds();
        setrms();
        nic.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        staffid = new javax.swing.JLabel();
        stafftype = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sst = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        minimize1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ptid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        wdid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rmid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ptname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bdid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jComboBox1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBox1VetoableChange(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 148, 220)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 30, 30));

        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 30, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, 30, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close Window-48.png"))); // NOI18N
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 150));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1330, 10));

        staffid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffid.setText("952042807v");
        jPanel1.add(staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 110, 30));

        stafftype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(stafftype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 110, 30));

        s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fields.png"))); // NOI18N
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 60, 30, 30));

        sst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fields.png"))); // NOI18N
        jPanel1.add(sst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hori separator.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 10, 140));

        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 40, 30));

        jLabel13.setText("Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 40, 30));

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 110, 30));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 110, 30));

        minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minimize Window-48.png"))); // NOI18N
        jPanel1.add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Change room or ward");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Patiant ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 20));

        ptid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptidActionPerformed(evt);
            }
        });
        ptid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptidKeyReleased(evt);
            }
        });
        jPanel1.add(ptid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Admit ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, -1));

        adid.setEditable(false);
        adid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adidActionPerformed(evt);
            }
        });
        jPanel1.add(adid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, -1));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 150, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("NIC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 120, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 251));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Wards");

        jTable2.setBackground(new java.awt.Color(255, 255, 251));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Price", "Status", "Available Beds"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 251));
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable2FocusGained(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(jComboBox1)
            );
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel11)
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 600, 350));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Ward ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 20));

        wdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wdidActionPerformed(evt);
            }
        });
        wdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wdidKeyReleased(evt);
            }
        });
        jPanel1.add(wdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Room ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, 20));

        rmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmidActionPerformed(evt);
            }
        });
        rmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rmidKeyReleased(evt);
            }
        });
        jPanel1.add(rmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Patiant Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 20));

        ptname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnameActionPerformed(evt);
            }
        });
        ptname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptnameKeyReleased(evt);
            }
        });
        jPanel1.add(ptname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Bed ID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 20));

        bdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdidActionPerformed(evt);
            }
        });
        bdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bdidKeyReleased(evt);
            }
        });
        jPanel1.add(bdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 120, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setText("Rooms");

        jTable4.setBackground(new java.awt.Color(255, 255, 251));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 251));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 370, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        try {
            System.exit(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_exitActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        try {
            this.setState(ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MinimizeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        try {
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void ptidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ptidActionPerformed

    private void adidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adidActionPerformed

    private void ptidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_ptidKeyReleased

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_nicActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:

        try {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jList1.grabFocus();
                jList1.setSelectedIndex(0);
            } else if (nic.getText().equals("")) {
                jScrollPane1.setVisible(false);
            } else {
                ResultSet rs = DB_connection.search("select * from patients_reg where Nic_no like '%" + nic.getText() + "%' and Status_no='3'");
                Vector v = new Vector();
                while (rs.next()) {
                    v.add(rs.getString("Nic_no"));
                }
                jList1.setListData(v);
                if (v.equals("")) {
                    jScrollPane1.setVisible(false);
                }
                jScrollPane1.setVisible(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_nicKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            nic.setText(jList1.getSelectedValue().toString());
            jScrollPane1.setVisible(false);
            ptid();
            checktype();

            //ptid.requestFocus();
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        nic.setText(jList1.getSelectedValue().toString());
        jScrollPane1.setVisible(false);
        ptid();
        checktype();

        //ptid.requestFocus();
    }//GEN-LAST:event_jList1MouseClicked

    private void wdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wdidActionPerformed

    private void wdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wdidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_wdidKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        rmid.setText("");
        wdid.setText((jTable2.getValueAt(jTable2.getSelectedRow(), 0)).toString());
        jComboBox1.removeAllItems();
        ResultSet sr1;
        try {
            sr1 = DB_connection.search("select * from avalible_beds where Wards_id='" + wdid.getText() + "' and Status_no='4'");

            while (sr1.next()) {
                jComboBox1.addItem(sr1.getString("Bed_no"));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jTable2MouseClicked

    private void rmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmidActionPerformed

    private void rmidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rmidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rmidKeyReleased

    private void ptnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptnameActionPerformed

    private void ptnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ptnameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int i = 1;
        
        try {
            DB_connection.iud("insert into admit2 (Admit_id,Patients_ID,Room_id,Ward_id,avalible_beds_No,Date,Time,Staff_id,Status_no) values('" + adid.getText() + "', '" + ptid.getText() + "', '" + rmid.getText() + "', '" + wdid.getText() + "', '" + bdid.getText() + "', '" + date.getText() + "', '" + time.getText() + "', '" + staffid.getText() + "', '" + i + "')");
            if (type=="room") {
                DB_connection.iud("update rooms set status_Status_no='4' where Room_id = '" + roomid + "'");
                DB_connection.iud("update rooms set status_Status_no='3' where Room_id = '" + rmid.getText() + "'");
                
            } else {
                DB_connection.iud("update avalible_beds set Status_no='4' where Wards_id = '" + wid + "' AND Bed_no = '" + bid + "'");
                DB_connection.iud("update avalible_beds set Status_no='3' where Wards_id = '" + wdid.getText() + "' AND Bed_no = '" + bdid.getText() + "'");
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "this patient has been moved once");
        }
            clearall();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdidActionPerformed

    private void bdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bdidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bdidKeyReleased

    private void jTable2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_jTable2FocusGained

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBox1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1VetoableChange

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
        try {
            bdid.setText(jComboBox1.getSelectedItem().toString());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jComboBox1FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearall();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        rmid.setText((jTable4.getValueAt(jTable4.getSelectedRow(), 0)).toString());
        wdid.setText("");
        bdid.setText("");
    }//GEN-LAST:event_jTable4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_room_or_ward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_room_or_ward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_room_or_ward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_room_or_ward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_room_or_ward().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Minimize;
    private javax.swing.JTextField adid;
    private javax.swing.JTextField bdid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField date;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton logout;
    private javax.swing.JLabel minimize1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField ptid;
    private javax.swing.JTextField ptname;
    private javax.swing.JTextField rmid;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel sst;
    private javax.swing.JLabel staffid;
    private javax.swing.JLabel stafftype;
    private javax.swing.JTextField time;
    private javax.swing.JTextField wdid;
    // End of variables declaration//GEN-END:variables

    private void load_time_and_date() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                d = new Date();
                sdf = new SimpleDateFormat("HH:mm:ss");
                time.setText(sdf.format(d));
                d = new Date();
                sdf = new SimpleDateFormat("YYYY/MM/dd");
                date.setText(sdf.format(d));
            }
        });
        t.start();
    }

    private void ptid() {
        try {
            ResultSet rs = DB_connection.search("select Patients_ID,Fname,Lname from patients_reg where Nic_no = '" + nic.getText() + "'");
            while (rs.next()) {
                ptid.setText(rs.getString("Patients_ID"));
                ptname.setText(rs.getString("Fname") + " " + rs.getString("Lname"));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setwrds() {
        try {
            ResultSet sr = DB_connection.search("select * from wards where status_Status_no ='1'");

            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();

            while (sr.next()) {

                Vector v = new Vector();

                v.add(sr.getString("Wards_id"));
                v.add(sr.getString("Name"));
                v.add(sr.getString("Type"));
                v.add(sr.getString("Price"));
                v.add("Available");

                //System.out.println(sr.getString("Symtom_ID"));
                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearall() {

        nic.setText("");
        ptid.setText("");
        ptname.setText("");
        wdid.setText("");
        bdid.setText("");
        rmid.setText("");
        DefaultTableModel d = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel d1 = (DefaultTableModel) jTable4.getModel();
        d.setRowCount(0);
        d1.setRowCount(0);
        setwrds();
        setrms();
        nic.requestFocus();
        
    }

    private void checktype() {
        try {
            String s1 = "";
            ResultSet rs1 = DB_connection.search("select Patients_ID from patients_reg where Nic_no= '" + nic.getText() + "'");
            while (rs1.next()) {
                s1 = rs1.getString("Patients_ID");
                System.out.println(s1);
            }
            ResultSet rs = DB_connection.search("select * from admit_details_room where Patients_ID = '" + s1 + "' and status_Status_no='1'");

            if (rs.next()) {
                System.out.println("yakow");
                //adidrm();
                type = "room";
                admitid = rs.getString("Admit_id");
                adid.setText(admitid);
                System.out.println(admitid);
                roomid = rs.getString("Room_id");
            } else {
                ResultSet rs2 = DB_connection.search("select * from admit_details_ward where Patients_ID = '" + s1 + "' and status_Status_no='1'");
                while (rs2.next()) {
                    admitid = rs2.getString("Admit_id");
                    adid.setText(rs2.getString("Admit_id"));
                    wid = rs2.getString("Wards_id");
                    bid = rs2.getString("avalible_beds_No");
                }

                System.out.println("bolau");
                //adidwrd();
                type = "ward";
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setrms() {
        try {
            ResultSet sr = DB_connection.search("select * from rooms where status_Status_no ='4'");
            DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();

            while (sr.next()) {

                Vector v = new Vector();

                v.add(sr.getString("Room_id"));
                v.add("available");
                //System.out.println(sr.getString("Symtom_ID"));

                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
