/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class Descharge extends javax.swing.JFrame {
    
    int i1 = 1;
    Date d;
    SimpleDateFormat sdf;
    String type;
    String admitid;
    String roomid;
    String wid;
    String bid;

    /**
     * Creates new form admit
     */
    public Descharge() {
        initComponents();
        exit.setContentAreaFilled(false);
        Minimize.setContentAreaFilled(false);
        load_time_and_date();
        jScrollPane1.setVisible(false);
        nic.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        staffid = new javax.swing.JLabel();
        stafftype = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sst = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        minimize1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ptid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jLabel8 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        bill = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rmid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ptname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 148, 220)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 30, 30));

        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 30, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, 30, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close Window-48.png"))); // NOI18N
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 150));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1330, 10));

        staffid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 110, 30));

        stafftype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(stafftype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 110, 30));

        s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fields.png"))); // NOI18N
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 60, 30, 30));

        sst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fields.png"))); // NOI18N
        jPanel1.add(sst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hori separator.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 10, 140));

        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 40, 30));

        jLabel13.setText("Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 40, 30));

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 110, 30));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 110, 30));

        minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minimize Window-48.png"))); // NOI18N
        jPanel1.add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Descharge");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Patiant ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        ptid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptidActionPerformed(evt);
            }
        });
        ptid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptidKeyReleased(evt);
            }
        });
        jPanel1.add(ptid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Descharge ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 100, -1));

        adid.setEditable(false);
        adid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adidActionPerformed(evt);
            }
        });
        jPanel1.add(adid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 150, -1));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("NIC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        bill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bill.setText("Pay Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel1.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 130, 100));

        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setText(" Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 130, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Status");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, 20));

        rmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmidActionPerformed(evt);
            }
        });
        rmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rmidKeyReleased(evt);
            }
        });
        jPanel1.add(rmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Patiant Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 20));

        ptname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnameActionPerformed(evt);
            }
        });
        ptname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptnameKeyReleased(evt);
            }
        });
        jPanel1.add(ptname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Admit ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Well", "Sick", "Dead" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        try {
            System.exit(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_exitActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        try {
            this.setState(ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MinimizeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        try {
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void ptidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptidActionPerformed
        // TODO add your handling code here:       
        //this.setVisible(false);
    }//GEN-LAST:event_ptidActionPerformed

    private void adidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adidActionPerformed

    private void ptidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ptidKeyReleased

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:       
        //this.setVisible(false);
        ptid();
        checktype();
        jScrollPane1.setVisible(false);
    }//GEN-LAST:event_nicActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:

        try {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jList1.grabFocus();
                jList1.setSelectedIndex(0);
            } else if (nic.getText().equals("")) {
                jScrollPane1.setVisible(false);
            } else {
                ResultSet rs = DB_connection.search("select * from patients_reg where Status_no='3' and Nic_no like '%" + nic.getText() + "%' ");
                Vector v = new Vector();
                while (rs.next()) {
                    v.add(rs.getString("Nic_no"));
                }
                jList1.setListData(v);
                if (v.equals("")) {
                    jScrollPane1.setVisible(false);
                }
                jScrollPane1.setVisible(true);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_nicKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            nic.setText(jList1.getSelectedValue().toString());
            jScrollPane1.setVisible(false);
            ptid();
            checktype();

            //ptid.requestFocus();
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        nic.setText(jList1.getSelectedValue().toString());
        jScrollPane1.setVisible(false);
        ptid();
        checktype();

        //ptid.requestFocus();
    }//GEN-LAST:event_jList1MouseClicked

    private void rmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmidActionPerformed

    private void rmidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rmidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rmidKeyReleased

    private void ptnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptnameActionPerformed

    private void ptnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ptnameKeyReleased

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int i = 1;
        String s;
        if (jComboBox1.getSelectedItem() == "Well") {
            s = "5";
        } else if (jComboBox1.getSelectedItem() == "Sick") {
            s = "6";
        } else {
            s = "7";
        }
        
        try {
            ResultSet rs = DB_connection.search("select * from admit2 where Admit_id='" + admitid + "'");
            if (rs.next()) {
                if (rs.getString("Room_id")=="") {
                    type="ward";
                    wid=rs.getString("Ward_id");
                    bid=rs.getString("avalible_beds_No");
                } else {
                    type="room";
                    roomid=rs.getString("Room_id");
                }
            }
            
            if (type == "ward") {
                
                DB_connection.iud("insert into descharge_ward_details (Descharge_id,Date,Admit_id,status_Status_no) values('" + adid.getText() + "','" + date.getText() + "','" + admitid + "','" + s + "')");
                DB_connection.iud("update admit_details_ward set status_Status_no='2' where Admit_id = '" + admitid + "'");
                DB_connection.iud("update avalible_beds set Status_no='4' where Wards_id = '" + wid + "' AND Bed_no = '" + bid + "'");
                
            } else if (type == "room") {
                DB_connection.iud("insert into descharge_room_details (Descharge_id,Date,Admit_id,status_Status_no) values('" + adid.getText() + "','" + date.getText() + "','" + admitid + "','" + s + "')");
                DB_connection.iud("update admit_details_room set status_Status_no='2' where Admit_id = '" + admitid + "'");
                DB_connection.iud("update rooms set status_Status_no='4' where Room_id = '" + roomid + "'");
                
            }
            if (jComboBox1.getSelectedItem() == "Dead") {
                DB_connection.iud("update patients_reg set Status_no='7' where Patients_ID = '" + ptid.getText() + "'");
                
            } else {
                DB_connection.iud("update patients_reg set Status_no='4' where Patients_ID = '" + ptid.getText() + "'");
            }
            //DB_connection.iud("insert into admit_details_room (Admit_id,Patients_ID,Room_id,Date,staff_Staff_id,status_Status_no) values('" + adid.getText() + "', '" + ptid.getText() + "', '" + rmid.getText() + "', '" + date.getText() + "', '" + dcid.getText() + "','" + i + "')");

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        clearall();

    }//GEN-LAST:event_saveActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        prophet_1_services11 p = new prophet_1_services11();
        p.setVisible(true);
        
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Minimize;
    private javax.swing.JTextField adid;
    private javax.swing.JButton bill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField date;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel minimize1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField ptid;
    private javax.swing.JTextField ptname;
    private javax.swing.JTextField rmid;
    private javax.swing.JLabel s1;
    private javax.swing.JButton save;
    private javax.swing.JLabel sst;
    private javax.swing.JLabel staffid;
    private javax.swing.JLabel stafftype;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables

    private void load_time_and_date() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                d = new Date();
                sdf = new SimpleDateFormat("HH:mm:ss");
                time.setText(sdf.format(d));
                d = new Date();
                sdf = new SimpleDateFormat("YYYY/MM/dd");
                date.setText(sdf.format(d));
                refresh();
            }
            
        });
        t.start();
    }
    
    private void adidrm() {
        
        try {
            ResultSet rs = DB_connection.search("select count(Admit_id)as x from admit_details_room");
            while (rs.next()) {
                int x = Integer.parseInt(rs.getString("x"));
                int x1 = x + 1;
                System.out.println(x1);
                adid.setText("DESRM" + x1);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
    
    private void adidwrd() {
        
        try {
            ResultSet rs = DB_connection.search("select count(Admit_id)as x from admit_details_ward");
            while (rs.next()) {
                int x = Integer.parseInt(rs.getString("x"));
                int x1 = x + 1;
                System.out.println(x1);
                adid.setText("DESWD" + x1);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
    
    private void ptid() {
        try {
            ResultSet rs = DB_connection.search("select Patients_ID,Fname,Lname from patients_reg where Nic_no = '" + nic.getText() + "'");
            while (rs.next()) {
                ptid.setText(rs.getString("Patients_ID"));
                ptname.setText(rs.getString("Fname") + " " + rs.getString("Lname"));
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void checktype() {
        try {
            String s1 = "";
            ResultSet rs1 = DB_connection.search("select Patients_ID from patients_reg where Nic_no= '" + nic.getText() + "'");
            while (rs1.next()) {
                s1 = rs1.getString("Patients_ID");
                System.out.println(s1);
            }
            ResultSet rs = DB_connection.search("select * from admit_details_room where Patients_ID = '" + s1 + "' and status_Status_no='1'");
            
            if (rs.next()) {
                System.out.println("yakow");
                adidrm();
                type = "room";
                admitid = rs.getString("Admit_id");
                rmid.setText(admitid);
                roomid = rs.getString("Room_id");
            } else {
                ResultSet rs2 = DB_connection.search("select * from admit_details_ward where Patients_ID = '" + s1 + "' and status_Status_no='1'");
                while (rs2.next()) {
                    admitid = rs2.getString("Admit_id");
                    rmid.setText(rs2.getString("Admit_id"));
                    wid = rs2.getString("Wards_id");
                    bid = rs2.getString("avalible_beds_No");
                }
                
                System.out.println("bolau");
                adidwrd();
                type = "ward";
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void refresh() {
        try {
            ResultSet rs = DB_connection.search("select * from bill where Admit_Id = '" + admitid + "' and status='0'");
            if (rs.next()) {
                System.out.println("aaaaaa");
                save.setVisible(true);
                bill.setVisible(false);
                save.setEnabled(true);
                bill.setEnabled(false);
            } else {
                System.out.println("bbbbbb");
                save.setVisible(false);
                bill.setVisible(true);
                save.setEnabled(false);
                bill.setEnabled(true);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void clearall() {
        nic.setText("");
        ptid.setText("");
        ptname.setText("");
        rmid.setText("");
        adid.setText("");
        jComboBox1.setSelectedItem("Well");
    }
    
}
